version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_E}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASS}
    ports:
      - "5050:80"
    env_file: .env 
    depends_on:
      - postgres
volumes:
  postgres-data: